### ISSUE TITLE
Remove src from published package

### ISSUE THREAD

**Issue by LucasPaganini** [gravwell/js-client#160]
Users are wrongly importing things from `"gravwell/src/*"`, this is causing many issues. Also, the source maps are not working properly anyways so we're not delivering any value by including the source files in the published package.

**Comment by ashnwade** [comment]
The Gravwell JavaScript Client is being retired. The latest version (Version 4.0.0) is compatible with Gravwell v5.4.7. The JS Client will not receive future updates and may not be compatible with future releases of Gravwell.

Please consult our API documentation for an up-to-date description of the Gravwell API https://api.docs.gravwell.io/
