### ISSUE TITLE
Don't return a File from backup API

### ISSUE THREAD

**Issue by michaelwisely** [gravwell/js-client#163]
This guy...

https://github.com/gravwell/js-client/blob/196942024d9e09f0df2c710f31b776e6aaa8850a/src/functions/system/backup.ts#L31

... won't work with Node (because of the `new File`). We should find a better way to return the backup we receive from the backend that will work with the browser and with Node.

Backup and restore issue: #26

**Comment by ashnwade** [comment]
The Gravwell JavaScript Client is being retired. The latest version (Version 4.0.0) is compatible with Gravwell v5.4.7. The JS Client will not receive future updates and may not be compatible with future releases of Gravwell.

Please consult our API documentation for an up-to-date description of the Gravwell API https://api.docs.gravwell.io/
