### ISSUE TITLE
Add method to relaunch the search from the SearchSubscription

### ISSUE THREAD

**Issue by LucasPaganini** [gravwell/js-client#174]
`SearchSubscription.relaunch(options)`

It should keep the same observables working.

Send a `close` message before relaunching new search.

Will be used to relaunch when the zoom is on the limit (#108) and will also be used by the renderers if they want to relaunch a search without breaking all the other renderings listening to the same search subscription

**Comment by ashnwade** [comment]
The Gravwell JavaScript Client is being retired. The latest version (Version 4.0.0) is compatible with Gravwell v5.4.7. The JS Client will not receive future updates and may not be compatible with future releases of Gravwell.

Please consult our API documentation for an up-to-date description of the Gravwell API https://api.docs.gravwell.io/
