### ISSUE TITLE
API errors should be typed

### ISSUE THREAD

**Issue by LucasPaganini** [gravwell/js-client#19]
Work with the backend team to map the possible errors with an `Error.code` or something like that that identifies the error so that we can tell the possible errors for each API request and the frontend can handle and internationalize them accordingly.

**Comment by ashnwade** [comment]
The Gravwell JavaScript Client is being retired. The latest version (Version 4.0.0) is compatible with Gravwell v5.4.7. The JS Client will not receive future updates and may not be compatible with future releases of Gravwell.

Please consult our API documentation for an up-to-date description of the Gravwell API https://api.docs.gravwell.io/
