### ISSUE TITLE
Generate a minified bundle for browsers

### ISSUE THREAD

**Issue by LucasPaganini** [gravwell/js-client#20]
`npm run build` should generate a very optimized file for browser, without any unnecessary dependencies and as small as possible

**Comment by ashnwade** [comment]
The Gravwell JavaScript Client is being retired. The latest version (Version 4.0.0) is compatible with Gravwell v5.4.7. The JS Client will not receive future updates and may not be compatible with future releases of Gravwell.

Please consult our API documentation for an up-to-date description of the Gravwell API https://api.docs.gravwell.io/
