### ISSUE TITLE
Specify the gravwell version support for each browser client version

### ISSUE THREAD

**Issue by LucasPaganini** [gravwell/js-client#24]
When releasing a version of this package on NPM, it should include a semver version describing which version of gravwell it's compatible to, eg. `4.x` for a client compatible to gravwell version between `4.0.0` and `5.0.0` (not including the latter).

When the client is instantiated, we should check the current gravwell version to see if it's compatible with it and display a warning otherwise.

**Comment by ashnwade** [comment]
The Gravwell JavaScript Client is being retired. The latest version (Version 4.0.0) is compatible with Gravwell v5.4.7. The JS Client will not receive future updates and may not be compatible with future releases of Gravwell.

Please consult our API documentation for an up-to-date description of the Gravwell API https://api.docs.gravwell.io/
