### ISSUE TITLE
List of Remote Kits is losing some details for image assets

### ISSUE THREAD

**Issue by ghost** [gravwell/js-client#271]
The assets are not telling us if it's a banner or cover.

**Comment by ashnwade** [comment]
The Gravwell JavaScript Client is being retired. The latest version (Version 4.0.0) is compatible with Gravwell v5.4.7. The JS Client will not receive future updates and may not be compatible with future releases of Gravwell.

Please consult our API documentation for an up-to-date description of the Gravwell API https://api.docs.gravwell.io/
