### ISSUE TITLE
Add usage examples to the README

### ISSUE THREAD

**Issue by LucasPaganini** [gravwell/js-client#30]
Usage suggestion (per Kris):
1. login
2. show active queries
3. logout

**Comment by ashnwade** [comment]
The Gravwell JavaScript Client is being retired. The latest version (Version 4.0.0) is compatible with Gravwell v5.4.7. The JS Client will not receive future updates and may not be compatible with future releases of Gravwell.

Please consult our API documentation for an up-to-date description of the Gravwell API https://api.docs.gravwell.io/
