### ISSUE TITLE
Remove workaround for backend issues

### ISSUE THREAD

**Issue by LucasPaganini** [gravwell/js-client#31]
Backend issue ids (internal access only):
- #2507
- #2509 
- #2505 
- #2426 
- #2425 
- #2290
- #2524 
- #2507 
- #2506 
- #2500 
- #2453 
- #2414 
- #2285

**Comment by ashnwade** [comment]
The Gravwell JavaScript Client is being retired. The latest version (Version 4.0.0) is compatible with Gravwell v5.4.7. The JS Client will not receive future updates and may not be compatible with future releases of Gravwell.

Please consult our API documentation for an up-to-date description of the Gravwell API https://api.docs.gravwell.io/
