### ISSUE TITLE
Update the parematers property type from AutoExtractor

### ISSUE THREAD

**Issue by Puszkarek** [gravwell/js-client#349]
### Description
The current interface says that the parameters only can be a string, but they also can be undefined.
We should update the Client and the Raw AutoExtractor type.
![image](https://user-images.githubusercontent.com/52247963/175375073-421eaf25-ba3f-42fc-93af-b42a50d4f79f.png)

### Notes:
The Client interface should have `parameters: string | null`

**Comment by ashnwade** [comment]
The Gravwell JavaScript Client is being retired. The latest version (Version 4.0.0) is compatible with Gravwell v5.4.7. The JS Client will not receive future updates and may not be compatible with future releases of Gravwell.

Please consult our API documentation for an up-to-date description of the Gravwell API https://api.docs.gravwell.io/
