### ISSUE TITLE
Actionable: parse command is not working properly

### ISSUE THREAD

**Issue by guilherme-lucio-unvoid-gravwell** [gravwell/js-client#383]
### What are the steps to reproduce this issue?

1. parse the following actionable into the `toActioanble` function:
```
{
    "ThingUUID": "dea75ef0-825d-4104-a9ac-7cba7d6d13ca",
    "UID": 1,
    "Global": false,
    "GUID": "f725abf0-167a-41e3-b8ca-afbadae6a052",
    "Name": "test-actionable",
    "Description": "",
    "Updated": "2022-08-05T17:31:17.383480183Z",
    "Contents": {
        "menuLabel": "",
        "actions": [
            {
                "name": "test-dashboard",
                "description": null,
                "placeholder": null,
                "command": {
                    "type": "dashboard",
                    "reference": 113154086364818,
                    "options": {}
                },
                "noValueUrlEncode": false,
                "start": {
                    "type": "timestamp",
                    "placeholder": null,
                    "format": null
                },
                "end": {
                    "type": "timestamp",
                    "placeholder": null,
                    "format": null
                }
            }
        ],
        "triggers": []
    },
    "Labels": null,
    "Disabled": false
}
```
### What happens?
Notice that the parsed `ActionableCommand.dashboardID` is a number

### What were you expecting to happen?
We should use `.toString()` when parsing a `reference` into the `dashboardID` and update the `RawActionableDashboardCommand` interface to:
```
export interface RawActionableDashboardCommand {
	type: 'dashboard';
	reference: RawUUID | RawNumericID;
	options?: { variable?: string };
}
```

### Any logs, error output, etc?
Request:
![image](https://user-images.githubusercontent.com/110203495/183134029-fb8789de-1552-4b85-b36d-5027659a1463.png)
Parsed Actionable:
![image](https://user-images.githubusercontent.com/110203495/183133856-ee364001-20e6-4fe4-b7ad-30c7acdae79f.png)

**Comment by guilherme-lucio-unvoid-gravwell** [comment]
This issue just happens if the user try to link a **_legacy_** `Dashboard` with an `Actionable`, because it may not have the `globalID`

![image](https://user-images.githubusercontent.com/110203495/208661068-909fab81-a861-4a41-8fc7-90d507cc82bd.png)

**Comment by ashnwade** [comment]
The Gravwell JavaScript Client is being retired. The latest version (Version 4.0.0) is compatible with Gravwell v5.4.7. The JS Client will not receive future updates and may not be compatible with future releases of Gravwell.

Please consult our API documentation for an up-to-date description of the Gravwell API https://api.docs.gravwell.io/
