### ISSUE TITLE
Allow users to cancel in-flight HTTP requests

### ISSUE THREAD

**Issue by michaelwisely** [gravwell/js-client#65]
The GUI data ingester allows users to cancel an upload after they start an ingest. This is handy, for example, if people realize they've chosen the wrong file.

Angular allows us to cancel in-flight HTTP requests [with the observable we get back](https://angular.io/guide/http#using-the-switchmap-operator), which is really nice. I did some digging, and they cancel the request like [this](https://github.com/angular/angular/blob/59680c2644456f9d48b78e713f7f225dfb5bb289/packages/common/http/src/xhr.ts#L329).

We should make sure we're able to cancel in-flight HTTP requests. It's important for the GUI ingester for sure, but it might be handy for other requests, too.

**Comment by ashnwade** [comment]
Close. Gen'd client does this!
