### ISSUE TITLE
Browser client issue when query has no renderer

### ISSUE THREAD

**Issue by LucasPaganini** [gravwell/js-client#80]
From gravgui#2480
 
### What are the steps to reproduce this issue?

1. Ran tag=syslog in my sandbox for the overview renderer sandbox

### What happens?

Error/crash

### What were you expecting to happen?

No error

### Any logs, error output, etc?

```
core.js:4002 ERROR TypeError: Cannot read property 'Lat' of undefined
    at to-search-entries.js:118
    at Array.map (<anonymous>)
```

### Any other comments?

It's assuming the renderer is pointmap when it's raw

**Comment by michaelwisely** [comment]
Tests using the raw renderer seem to be passing: 

https://github.com/gravwell/js-client/pull/81/checks?check_run_id=1816654420#step:8:123
